### PR TITLE
Add UUIDv4 validator

### LINKED ISSUE #14: Add a UUID validator

### PR DESCRIPTION
**Pull request by rtuin**
As discussed last Friday, here's a UUIDv4 rule. Should close #14

### CODE REVIEW

**Comment by RickvdStaaij** [comment]
Is it required to go with `uuidv4()`? If v4 is most commen, could we make that default for and rename the validator to `uuid()`? Maybe even better: `$v->required('uuid')->uuid($version = 4);`

**Comment by rtuin** [comment]
Of course it's not required, but it's the most self-documenting solution I could think of.

**Comment by berry-langerak** [comment]
I'm thinking that we could solve that with a few `const`s as well:

```php
use Particle\Validator\Rule\Uuid;

$v = new Validator;
$v->required('foo')->uuid(Uuid::V4);
```

Of course, the v4 would be the default (because it is the most common, from my own experience). So the API would read:

```php
public function uuid($version = Uuid::V4)
```

What do you guys think?

**Comment by rtuin** [comment]
If constants are the preferred way to define variations in the validation rules, that's good for me. Readable for sure.

For a consistent API all other validation rules should also use constants to indicate variations, but I guess that's obvious. Haven't checked but I think there aren't any rules that need changes for that right now.

What do you think of aliasing the variantions, for example ->uuidv4() will proxy to ->uuid(Uuid::V4)?

**Comment by berry-langerak** [comment]
@rtuin Well, there are actually a few rules that could use a const instead of `bool` configuration, such as $allowSpaces in Alnum and Alpha. I think those need to be changed too. Anyway, could you adapt this PR to `$v->required('guid')->uuid(Uuid::v4)`, or would you like me to do it?

**Comment by rtuin** [comment]
Sure, be my guest and adapt the changes if you want to get this in. I just closed my laptop for today :)

**Comment by RickvdStaaij** [comment]
Constants would be a nice solution, cool!

**Pull request merged**
