### PR TITLE
Add a validation rule for an integer value

### PR DESCRIPTION
**Pull request by rtuin**
I was validating a negative number value with the digits validator the other day, but obviously the `-` is not considered a digit.

### CODE REVIEW

**Comment by RickvdStaaij** [comment]
I was looking between some overlap between `->digits()` and your new `->integer()`, but I guess it's pretty different after all.

Just a thought, wouldn't `->number($allowNegative = false)` be an option too? Then dropping `->digits()` and `->integer()`.

Nice PR though!

**Comment by rtuin** [comment]
I thought about that, but a number is more than just an integer. For example:
```
```

**Comment by RickvdStaaij** [comment]
Hmm I didn't know about those differences, makes sense to have separate ones then.

But for the parameters, if you want to know what false would be, pressing `ctrl + p` would be enough:
image
Same would go for `->alnum($allowSpaces)`.

**Comment by berry-langerak** [comment]
Also, you could go for `$v->integer(Integer::ALLOW_NEGATIVE);` instead of `true` or `false`, if you want more clarity. However, in the case you *don't* want to allow negatives, you could solve this with:

```php
$v = new Validator;
$v->integer()->between(0, null);
```

So I think the current code is sufficient and readable. Merging :)

**Comment by berry-langerak** [comment]
Also, thanks a bundle, @rtuin (and @RickvdStaaij for reviewing)! Awesome to not be the only one working on this :)

**Pull request merged**
