### PR TITLE
Phone Number Rule

### PR DESCRIPTION
**Pull request by camcima**
Created new Phone rule to validate phone number using a PHP library based on Google's libphonenumber library.

### CODE REVIEW

**Comment by RickvdStaaij** [comment]
For this goes the same as the credit card validator:

> @camcima Thanks a lot for this addition, but I'm afraid we're not going to accept it. Particle is made to be the smallest possible package, but with supporting the most important validations. For this reason we don't want to have any third party dependencies. Everyone is free to extend the validator to be able to add their own custom validations, like this credit card check for example. It's a nice addition but I don't think this should be in particle by default.

Thanks a lot for your addition nevertheless :D

**Comment by camcima** [comment]
No problem. But can you please explain me what is the reason behind not having external dependencies? Isn't it the point of having things like Packagist and composer? Why reinvent the wheel if someone has already done it?

**Comment by berry-langerak** [comment]
Hi @camcima, I have had a talk about this PR (and the one for CC validation) with @RickvdStaaij. My original reasoning behind "not having dependencies" was based mostly on the fact that I don't want to have dependencies on framework implementations etc. The reason is that I wanted it to work stand-alone (i.e. not bound to any framework).

As such, I have no problems with having external dependencies, as long as they don't lock us into a certain framework eco-system. libphonenumber certainly doesn't.

@RickvdStaaij will check out libphonenumber (because it would be nice to have a view on its stability, etc) and merge this PR if accepted.

Thanks for your contribution!

**Comment by RickvdStaaij** [comment]
Looking into the dependencies of "byrokrat/checkdigit":
> requires
> * ext-mbstring: *

[PHP.net](http://php.net/manual/en/mbstring.installation.php):

> mbstring is a non-default extension. This means it is not enabled by default. You must explicitly enable the module with the configure option. See the Install section for details.

Which would make it a problem to install particle/validator if that's not enabled on your server.

What do you think @camcima / @berry-langerak?

**Comment by RickvdStaaij** [comment]
We already use mb_ functions in filter too by the way, never saw a complaint there. This is probably not blocking :)

**Comment by nesl247** [comment]
Also after a bit of research, at least for PHP 5, a lot of distributions of linux, brew for mac, etc., include mbstring in the default build.

**Comment by RickvdStaaij** [comment]
@nesl247 thank you for checking that!

@camcima if you can fix the merge conflict we are good to go! :+1:

**Comment by camcima** [comment]
Conflicts resolved.

**Comment by RickvdStaaij** [comment]
Perfect, thank you! :+1:

**Comment by RickvdStaaij** [comment]
All latest new validators have been released in [v2.1.0](https://github.com/particle-php/Validator/releases/tag/v2.1.0) :)

**Comment by berry-langerak** [comment]
Awesome, yay! Thanks again for contributing, @camcima!

**Pull request merged**
