### PR TITLE
Fix: Add PHP 5.4, 5.5, and 7 to build matrix

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] adds PHP 5.4, PHP 5.6 and 7 to the build matrix

### CODE REVIEW

**Comment by localheinz** [comment]
1979f08 is basically stolen from https://github.com/particle-php/Filter/blob/master/.travis.yml.

**Comment by RickvdStaaij** [comment]
Nice improvement, but what about 5.6, why not test that one too?

Also, we should make Validator ready for 7.0, as the alpha was already released, but that's for another PR. We can let 7.0 out for now.

**Comment by localheinz** [comment]
@RickvdStaaij 

Added all of them to the build matrix, but allowed PHP7 to fail for now, see [this](https://travis-ci.org/particle-php/Validator/jobs/68602148#L167)

>PHP Fatal error:  Cannot use Particle\Validator\Rule\Bool as Bool because 'Bool' is a special class name in /home/travis/build/particle-php/Validator/tests/Rule/BoolTest.php on line 4
Fatal error: Cannot use Particle\Validator\Rule\Bool as Bool because 'Bool' is a special class name in /home/travis/build/particle-php/Validator/tests/Rule/BoolTest.php on line 4
The command "php vendor/bin/phpunit --coverage-clover=coverage.clover" exited with 255.

**Comment by RickvdStaaij** [comment]
This is great, thanks! I didn't know `allow_failures` was an option :smile:

**Comment by RickvdStaaij** [comment]
@localheinz To fix that issue, we have some renaming to do: https://wiki.php.net/rfc/reserve_more_types_in_php_7

**Pull request merged**
