### PR TITLE
Return null instead of false if a key (part) does not exist.

### PR DESCRIPTION
**Pull request by jaapverloop**

### CODE REVIEW

**Comment by berry-langerak** [comment]
Hi @jaapverloop, thanks for the pull request! I think the PR you've submitted is quite correct, although I would like to see a unit test proving that it now works as intended (just to make sure we don't have any BC breaks in the future).

**Comment by jaapverloop** [comment]
@berry-langerak I've added some simple tests to cover this specific use case.

**Comment by RickvdStaaij** [comment]
@berry-langerak @jaapverloop is this still a valid fix? Or was there another fix already merged for this?

**Comment by jaapverloop** [comment]
AFAIK this PR is still valid, but this commit https://github.com/particle-php/Validator/commit/d45950e330fbc88f20634f1de5d73dcf1e81309a removes non-existing keys from the result. So it's seems a little redundant.

**Comment by berry-langerak** [comment]
In which case, I'll close it for now. If there are still issues, please let me or @RickvdStaaij know. Thanks for your contributions, @jaapverloop!

**Pull request closed without merging**
